In [31]:
import pandas as pd

#需要安装额外库：pip install chardet
import chardet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
#导入数据
pro_data = pd.read_csv(r'D:\VScode\AllCode\美赛\2025\data\2025_Problem_C_Data\2025_Problem_C_Data\summerOly_programs.csv',encoding = "Windows-1252")

In [33]:
print("sport:",pro_data["Sport"].unique().size)
print("discipline:",pro_data["Discipline"].unique().size)
print("code:",pro_data["Code"].unique().size)
#disicipline和sport governing没啥用

sport: 51
discipline: 71
code: 71

In [34]:
#code存在缺失值，手动填充
#s5:因为项目取消，直接用0填充
#.:展示项目，直接用0代替
#部分项目没有code，用缩写代替
pro = pro_data.copy()
#pro.fillna(0,inplace = True)
pro = pro.replace("•",0)
pro.loc[39,"Code"] = "JDP"
pro.loc[47,"Code"] = "RQE"
#删除冰雪项目
pro = pro.drop(index = [69,70])
#删除没用的discipline和sportbody
pro = pro.drop(columns = ["Discipline","Sports Governing Body","1906*"])

In [35]:
pro.head()

,Sport,Code,1896,1900,1904,1908,1912,1920,1924,1928,...,1988,1992,1996,2000,2004,2008,2012,2016,2020,2024
0,Aquatics,SWA,0,0,0,0,0,0,0,0,...,2,2,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
1,Aquatics,DIV,0,0,2,2,4,5,5,4,...,4,4,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Aquatics,OWS,0,0,0,0,0,0,0,0,...,0,0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
3,Aquatics,SWM,4,7,9,6,9,10,11,11,...,31,31,32.0,32.0,32.0,32.0,32.0,32.0,35.0,35.0
4,Aquatics,WPO,0,1,1,1,1,1,1,1,...,1,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [36]:
pro.to_csv(r"D:\VScode\AllCode\美赛\2025\code\clean_data\pro_clean.csv")